version: "3.5"
services:
  db:
    image: "postgres"
    restart: always
    command: postgres -c default_transaction_isolation=serializable
    environment:
      POSTGRES_USER: atp
      POSTGRES_PASSWORD: atp
      POSTGRES_DB: atp
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  postgres: